name: CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch: # 手动触发部署

# 避免重复任务浪费
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # 1️⃣ 变更检测
  changes:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      app1: ${{ steps.filter.outputs.app1 }}
      app2: ${{ steps.filter.outputs.app2 }}
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            web:
              - 'apps/web/**'
            app1:
              - 'apps/app1/**'
            app2:
              - 'apps/app2/**'
            packages:
              - 'packages/**'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - 'turbo.json'
              - 'tsconfig*.json'

  # 2️⃣ 构建 web
  build-web:
    needs: changes
    if: |
      github.event_name == 'pull_request' &&
      (needs.changes.outputs.web == 'true' || needs.changes.outputs.packages == 'true') &&
      needs.changes.outputs.app1 != 'true' && needs.changes.outputs.app2 != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint --filter web
      - run: pnpm typecheck --filter web
      - run: pnpm build --filter web
      - run: pnpm test --filter web

  # 3️⃣ 构建 app1
  build-app1:
    needs: changes
    if: |
      github.event_name == 'pull_request' &&
      (needs.changes.outputs.app1 == 'true' || needs.changes.outputs.packages == 'true') &&
      needs.changes.outputs.app2 != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint --filter app1
      - run: pnpm typecheck --filter app1
      - run: pnpm build --filter app1
      - run: pnpm test --filter app1

  # 4️⃣ 构建 app2
  build-app2:
    needs: changes
    if: |
      github.event_name == 'pull_request' &&
      (needs.changes.outputs.app2 == 'true' || needs.changes.outputs.packages == 'true') &&
      needs.changes.outputs.app1 != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint --filter app2
      - run: pnpm typecheck --filter app2
      - run: pnpm build --filter app2
      - run: pnpm test --filter app2

  # 5️⃣ 全量构建兜底
  build-all:
    needs: changes
    if: |
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        (
          (needs.changes.outputs.app1 == 'true' && needs.changes.outputs.app2 == 'true') ||
          (needs.changes.outputs.web == 'true' && (needs.changes.outputs.app1 == 'true' || needs.changes.outputs.app2 == 'true'))
        )
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm test

  # 6️⃣ Docker 打包与推送（仅手动触发）
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      # ✅ 复用 pnpm 缓存
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile

      # ✅ 构建 Docker 镜像，挂载 .pnpm-store 提速
      - name: Build Docker images
        run: |
          docker build --build-arg PNPM_STORE=/root/.local/share/pnpm/store \
            -t myorg/web:latest -f apps/web/Dockerfile .
          docker build --build-arg PNPM_STORE=/root/.local/share/pnpm/store \
            -t myorg/app1:latest -f apps/app1/Dockerfile .
          docker build --build-arg PNPM_STORE=/root/.local/share/pnpm/store \
            -t myorg/app2:latest -f apps/app2/Dockerfile .

      # ✅ 推送到 Docker Hub
      - name: Push Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push myorg/web:latest
          docker push myorg/app1:latest
          docker push myorg/app2:latest
