name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 添加 Node.js 和 pnpm 环境（如果 Dockerfile 需要构建步骤）
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docker images
        run: |
          set -e  # 遇到错误立即退出
          docker build -t maple214/web:${{ github.event.inputs.tag }} -f apps/web/Dockerfile . --build-arg BUILDKIT_INLINE_CACHE=1
          docker build -t maple214/app1:${{ github.event.inputs.tag }} -f apps/app1/Dockerfile . --build-arg BUILDKIT_INLINE_CACHE=1
          docker build -t maple214/app2:${{ github.event.inputs.tag }} -f apps/app2/Dockerfile . --build-arg BUILDKIT_INLINE_CACHE=1

      - name: Push Docker images
        run: |
          set -e  # 遇到错误立即退出
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push maple214/web:${{ github.event.inputs.tag }}
          docker push maple214/app1:${{ github.event.inputs.tag }}
          docker push maple214/app2:${{ github.event.inputs.tag }}
