version: '3.8'

services:
  app1:
    image: crpi-x3f046xkcyg3q9cl.cn-hangzhou.personal.cr.aliyuncs.com/maple_214/app1:latest
    container_name: app1
    restart: always
    ports:
      - '5001:80'

  app2:
    image: crpi-x3f046xkcyg3q9cl.cn-hangzhou.personal.cr.aliyuncs.com/maple_214/app2:latest
    container_name: app2
    restart: always
    ports:
      - '5002:80'
  maple-blog:
    image: crpi-x3f046xkcyg3q9cl.cn-hangzhou.personal.cr.aliyuncs.com/maple_214/maple-blog:latest
    container_name: maple-blog
    restart: always
    ports:
      - '5003:80'
  web:
    image: crpi-x3f046xkcyg3q9cl.cn-hangzhou.personal.cr.aliyuncs.com/maple_214/web:latest
    container_name: web
    restart: always
    depends_on:
      - app1
      - app2
    ports:
      - '80:80'
