# 生产环境用
services:
  app1:
    image: maple214/app1:latest
    container_name: app1
    restart: always
    ports:
      - '5001:80'

  app2:
    image: maple214/app2:latest
    container_name: app2
    restart: always
    ports:
      - '5002:80'

  web:
    image: maple214/web:latest
    container_name: web
    restart: always
    depends_on:
      - app1
      - app2
    ports:
      - '80:80'
